export interface IColors {
  primary: string,
  secondary: string,
  complementary: string,
  light: string,
  lightGrey: string,
  grey: string,
  dark: string,
  success: string,
  info: string,
  warning: string,
  danger: string,
  blue: string,
  indigo: string,
  purple: string,
  pink: string,
  red: string,
  orange: string,
  yellow: string,
  green: string,
  teal: string,
  cyan: string,
}